### ISSUE TITLE
emerge of buildkernel fails due to ebuild not satisfied.

### ISSUE THREAD

**Issue by GhostOnTheFiber** [sakaki-/sakaki-tools#10]
Hey, 
My last emerge failed with the error:

 `emerge: there are no ebuilds to satisfy ">=app-crypt/sbsigntools-0.6-r1".`. 

It seems like it might be an error in the ebuild file for buildkernel on line 26 [link](https://github.com/sakaki-/sakaki-tools/blob/9ee72181a0dfa3e1285ecca010a811227d9c86fc/sys-kernel/buildkernel/buildkernel-1.0.30-r1.ebuild#L26).

I think that the line should be `>=app-crypt/sbsigntool-0.6-r1` instead of `>=app-crypt/sbsigntools-0.6-r1` as there is no ebuild for sbsigntools but there is one for sbsigntool.

**Comment by sakaki-** [comment]
`app-crypt/sbsigntool` was [recently renamed](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=c638678c995810739309b8582e90a3957bc98615) to `app-crypt/sbsigntools` in the main Gentoo repo, so if you update this you should find `buildkernel` will emerge again

**Comment by necrose99** [comment]
https://packages.gentoo.org/packages/app-crypt/sbsigntools
https://gitweb.gentoo.org/repo/gentoo.git/tree/app-crypt/sbsigntools/sbsigntools-0.9.1-r1.ebuild

**Comment by GhostOnTheFiber** [comment]
Hey, sorry for not closing this issue earlier. Syncing and running buildkernel again fixed the issue. 
Thanks for the help!
