### ISSUE TITLE
app-crypt/staticgpg-1.4.16 fails to build

### ISSUE THREAD

**Issue by frunzales** [sakaki-/sakaki-tools#21]
Hi,

Build log attached - emerge --info output attached as well. Note that I'm trying to compile this with gcc 10.1.0::gentoo and binutils 2.34-r1::gentoo.
 
[emergeinfo.txt](https://github.com/sakaki-/sakaki-tools/files/4659157/emergeinfo.txt)
[staticgpg.txt](https://github.com/sakaki-/sakaki-tools/files/4659141/staticgpg.txt)

**Comment by Armoken** [comment]
@sakaki- hi, you forgot to update sys-kernel/buildkernel dependencies

**Comment by sakaki-** [comment]
Oops, forgot that was an `=` not a `~` dep ><
Thanks @Armoken, hopefully should be fixed now.
