### ISSUE TITLE
Dependency conflict between plymouth and buildkernel

### ISSUE THREAD

**Issue by fcsager** [sakaki-/sakaki-tools#23]
Hi,
It appears sys-boot/plymouth was updated upstream in the main gentoo repository, and the gdm USE flag was removed from the ebuild. This now creates a conflict with sys-kernel/buildkernel. The warning message from portage is below.

WARNING: One or more updates/rebuilds have been skipped due to a dependency conflict:

sys-boot/plymouth:0

  (sys-boot/plymouth-0.9.5:0/0::gentoo, ebuild scheduled for merge) USE="gtk libkms pango (split-usr) udev -debug -static-libs" ABI_X86="(64)" conflicts with
    >=sys-boot/plymouth-0.8.8-r4[gdm,libkms,pango] required by (sys-kernel/buildkernel-1.0.36-r1:0/0::sakaki-tools, installed) USE="plymouth" ABI_X86="(64)"

**Comment by sakaki-** [comment]
Thanks for the heads up, I'll take a look.
Best, sakaki
