### ISSUE TITLE
sys-kernel/buildkernel ebuild dependencies

### ISSUE THREAD

**Issue by spijet** [sakaki-/sakaki-tools#5]
Hello again!

I've started using your `buildkernel` and `genup` scripts recently (I've finally moved my system to LUKS ^_^) and they work just right for me!
There's a one minor problem, however — if I undestand it right, `buildkernel`'s ebuild contains hard dependency on one of three kernel sources variations from the Gentoo tree: `gentoo-sources`, `hardened-sources` and `aufs-sources`. As for me, I use `pf-sources` to build a kernel with post-factum's patchset, since it gives me a bit lower power consumption (3-6 watts instead of 5-8 while on idle or somewhat 'light' load) and includes the UKSM patch. `buildkernel` works with `pf-sources` kernel without problems, but this dependency requires me to have 2 sets of kernel sources installed.

This could be worked around if `buildkernel`'s ebuild would specify `virtual/linux-sources` as a dependency instead.

**Comment by sakaki-** [comment]
Sounds sensible. If you submit a PR to that effect (for a `buildkernel-1.0.25-r1` ebuild) to `sakaki-tools` I will merge and test it. Thanks!

**Comment by spijet** [comment]
You mean the buildkernel script itself, or just the ebuild?

**Comment by sakaki-** [comment]
I think only the ebuild needs modding - the deps are changing but not the script itself, so no need to version bump it. Just make a new revision of the ebuild.

**Comment by sakaki-** [comment]
I modified my original comment to that effect shortly after writing it, but you were too quick for me ^-^

**Comment by spijet** [comment]
Yeah, I've responded via email right after I got it. :)
OK, time to figure out how to do PRs properly!

ADD: Also, it's possible to add/remove a dependency on linux firmware using `virtual/linux-sources`'s `firmware` USE flag. This could be useful for de-blobbed installations (I'm using firmwares for my Intel Wi-Fi card, so it's of little use to me, but).

**Comment by spijet** [comment]
Done, the PR is here: #6 .

Please let me know if I'm doing anything wrong. :)

**Comment by sakaki-** [comment]
Closed by #7 (squash merged as commit 98b307e8bbb82e41fb035c3668ab711b0c3c845a)

**Comment by spijet** [comment]
I can confirm that buildkernel works well now and asks me if I want to upgrade my kernel when newer sources are available. ^_^

Before this dependency change it always asked me to upgrade (for example) from `pf-sources-4.12_p6` to `gentoo-sources-4.12.6`, even if I had `pf-sources-4.12_p7` ebuild ready and installed :D
