### ISSUE TITLE
buildkernel Runtime Dependency Renamed

### ISSUE THREAD

**Issue by corrmaan** [sakaki-/sakaki-tools#9]
buildkernel-1.0.30.ebuild has >=app-crypt/sbsigntool-0.6-r1 as a runtime dependency. app-crypt/sbsigntool was renamed to app-crypt/sbsigntools (https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=c638678c995810739309b8582e90a3957bc98615)

**Comment by sakaki-** [comment]
PS thanks for reporting this!

**Comment by corrmaan** [comment]
No worries, thanks for the quick commit! And thanks for all your work on an excellent gentoo EFI install guide and all the tools that go along with it.
